<a href="https://colab.research.google.com/github/artemisIsNotBeam/Soccer-player-salaries/blob/main/Soccer_player_salaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Imports

In [27]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
# i need to import regression and train test split

fixing the data

In [40]:
data = pd.read_csv("drive/MyDrive/raw_wages.csv")

data['Salary'] = data['Salary'].str.replace(',', '')
data['Salary'] = data['Salary'].str.replace('p/a','')
data['Salary'] = data['Salary'].str.replace('€','').astype(float)

data['EU National'] = data['EU National'].replace({' Yes         ': 1, ' No          ': 0}).astype(float)

#data['AT Apps'] = data['AT Apps'].map({'-':0})
data['CR'] = data['CR'].str.replace(',', '')

data['Last Trans. Fee'] = data['Last Trans. Fee'].str.replace('€','')
data['Last Trans. Fee'] = data['Last Trans. Fee'].str.replace('M','')
data['Last Trans. Fee'] = data['Last Trans. Fee'].str.replace('K','')
data['Last Trans. Fee'] = data['Last Trans. Fee'].str.replace('-','0').astype(float)

data['AT Apps'] = data['AT Apps'].str.replace('-','0')
data['AT Apps'] = data['AT Apps'].str.strip().astype(float)

#print(data['AT Apps'].unique())
#remove the At apps that are -
justPrem = data[data['Division'].str.contains('Premier')]

justPrem.head(10)

,Name,Club,Division,Based,Nat,EU National,Caps,AT Apps,Position,Age,CR,Begins,Expires,Last Club,Last Trans. Fee,Salary
15,- -,-,Premier League ...,England (Premier League) ...,BRA,1.0,21.0,327.0,,30.0,8864,15/8/2023,30/6/2028,Benfica,41.0,22733000.0
20,- -,-,Premier League ...,England (Premier League) ...,ENG,0.0,82.0,352.0,,28.0,8158,13/7/2022,30/6/2027,Man City,55.0,21225000.0
21,- -,-,Premier League ...,England (Premier League) ...,EGY,0.0,89.0,401.0,,31.0,9325,1/7/2022,30/6/2025,Roma,40.0,21225000.0
24,- -,-,Premier League ...,England (Premier League) ...,NOR,1.0,25.0,190.0,,23.0,9406,1/7/2022,30/6/2027,Dortmund,59.0,20619000.0
25,- -,-,Premier League ...,England (Premier League) ...,BEL,1.0,99.0,427.0,,32.0,9503,5/7/2021,30/6/2025,Wolfsburg,63.0,20619000.0
30,- -,-,Premier League ...,England (Premier League) ...,FRA,1.0,10.0,174.0,,25.0,8100,1/7/2023,30/6/2029,RB Leipzig,60.0,18193000.0
31,- -,-,Premier League ...,England (Premier League) ...,BRA,1.0,71.0,357.0,,31.0,7892,22/8/2022,30/6/2026,Real Madrid,70.0,18193000.0
32,- -,-,Premier League ...,England (Premier League) ...,ENG,0.0,53.0,241.0,,25.0,8003,18/7/2023,30/6/2028,,0.0,18193000.0
40,- -,-,Premier League ...,England (Premier League) ...,ENG,0.0,23.0,163.0,,23.0,7200,23/7/2021,30/6/2026,Dortmund,85.0,16677000.0
41,- -,-,Premier League ...,England (Premier League) ...,ENG,1.0,32.0,280.0,,27.0,8289,5/8/2021,30/6/2027,Aston Villa,117.0,16374000.0

In [41]:
y = justPrem['Salary']
x = justPrem[['EU National', 'Caps','AT Apps','CR','Age','Last Trans. Fee']]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

Training

In [43]:
model = LinearRegression()
fited = model.fit(x_train,y_train)

In [54]:
print(model.coef_)

[206941.66731526  25427.26145884   1105.93938037    704.52948902
 -53014.37890987   -419.85682144]

Loss

In [50]:
y_pred = model.predict(x_test)

print(model.score(x_test,y_test))
print(model.score(x_train,y_train))

0.4576496489148537
0.4171220017226571

In [53]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("loss")
print(f'Mean absolute error: {mae:.2f}')
print(f'Mean squared error: {mse:.2f}')
print(f'Root mean squared error: {rmse:.2f}')

loss
Mean absolute error: 834654.83
Mean squared error: 2183523043547.25
Root mean squared error: 1477674.88